server:
  port: 9007

spring:
  datasource:
     url: jdbc:mysql:///hrm-user?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8


hrm:
  swagger:
    title: 用户管理服务
    description: 用户管理服务接口

