server:
  port: 9527


zuul:
  prefix: /services  #指定一个全局前缀servers
  ignored-services: "*"  # 忽略指定微服务，多个微服务之间使用逗号分隔
  routes:
    system:
      path: /system/**
      serviceId: SYSTEM-SERVICE
    course:
      path: /course/**
      serviceId: COURSE-SERVICE
    fastdfs:
      path: /file/**
      serviceId: FASTDFS-SERVICE
